### PR TITLE
New headline, some copy edits

### PR DESCRIPTION
**Pull request by cloudhead**
Signed-off-by: Alexis Sellier <self@cloudhead.io>

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
The emojis might look better at `font-size: 3rem;`
image

**Comment by cloudhead** [comment]
> 

that's the size they already are at though?

**Comment by brandonhaslegs** [comment]
Yeah when I checked it out there were small. Looks good!

**Comment by cloudhead** [comment]
This repo has moved to radicle, feel free to delete it here.

**Pull request closed without merging**
